blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discusiones de la Comunidad
    url: https://github.com/dvchinx/pyjava/discussions
    about: Para preguntas generales, ideas y discusiones de la comunidad
  - name: ğŸ“– DocumentaciÃ³n
    url: https://github.com/dvchinx/pyjava/blob/main/README.md
    about: Consulta la documentaciÃ³n oficial del proyecto